# Generated by Django 4.0.2 on 2022-03-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dortoires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='sexe',
            field=models.CharField(default='M', max_length=5),
        ),
    ]
