# Generated by Django 4.0.2 on 2022-03-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dortoires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dortoire',
            name='occupation',
            field=models.IntegerField(default=0),
        ),
    ]
