# Generated by Django 4.0.2 on 2022-07-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('paroisse', models.CharField(max_length=255)),
                ('poste', models.CharField(max_length=255)),
                ('commission', models.CharField(max_length=100)),
                ('sexe', models.CharField(default='M', max_length=5)),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
    ]
