# Generated by Django 4.0.2 on 2022-07-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisateur',
            name='sexe',
            field=models.CharField(default='M', max_length=15),
        ),
    ]
