# Generated by Django 4.0.2 on 2022-03-06 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='createdat',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 6, 4, 46, 52, 875760)),
        ),
    ]
