# Generated by Django 4.0.2 on 2022-03-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
