# Generated by Django 4.0.2 on 2022-03-06 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_participant_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='createdat',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
