# Generated by Django 4.0.2 on 2022-03-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_participant_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEncadreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='encadreur',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
