# Generated by Django 4.0.2 on 2022-03-06 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_participant_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='address',
        ),
    ]
