# Generated by Django 4.0.2 on 2022-03-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_codeencadreur_participant_encadreur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeencadreur',
            name='code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
