# Generated by Django 4.0.2 on 2022-03-06 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_participant_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='createdat',
        ),
        migrations.AddField(
            model_name='participant',
            name='create_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='participant',
            name='createat',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
