# Generated by Django 4.0.2 on 2022-03-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_codeencadreur_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='participant',
            name='cni',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='polo',
            field=models.CharField(default='L', max_length=5),
        ),
        migrations.AddField(
            model_name='participant',
            name='type',
            field=models.CharField(default='Laïc', max_length=20),
        ),
    ]
