# Generated by Django 4.0.2 on 2022-03-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_participant_age_participant_cni_participant_polo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='photo',
            field=models.TextField(null=True),
        ),
    ]
