# Generated by Django 4.0.2 on 2022-03-06 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_participant_createdat_participant_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='createat',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
