# Generated by Django 4.0.2 on 2022-03-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_participant_createat'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
