# Generated by Django 4.0.2 on 2022-03-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_participant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='paye',
            field=models.BooleanField(default=False),
        ),
    ]
