# Generated by Django 4.0.2 on 2022-03-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_participant_paye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='paye',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
