# Generated by Django 4.0.2 on 2022-03-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_participant_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='allergies',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='groupe_sanguin',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='maladies',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
