# Generated by Django 4.0.2 on 2022-03-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_participant_allergies_participant_groupe_sanguin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='produit',
            field=models.BooleanField(default=False),
        ),
    ]
