# Generated by Django 4.0.2 on 2022-05-11 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_participant_paye'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeEncadreur',
        ),
    ]
